"""add_max_steps_to_simulation

Revision ID: 0016
Revises: 0015
Create Date: 2026-04-08 12:00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0016'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulations', sa.Column('max_steps', sa.Integer(), nullable=True))
    # 设置现有记录的默认值为 10
    op.execute("UPDATE simulations SET max_steps = 10 WHERE max_steps IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulations', 'max_steps')
    # ### end Alembic commands ###
