"""add_counterfactual_tables

Revision ID: 0017
Revises: 0016
Create Date: 2026-04-08 13:00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0017'
down_revision: Union[str, None] = '0016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjusted! ###
    
    # Create counterfactual_scenarios table
    op.create_table('counterfactual_scenarios',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('scenario_type', sa.Enum('POLITICAL', 'ECONOMIC', 'SOCIAL', 'TECHNOLOGY', 'ENVIRONMENT', 'CUSTOM', name='scenariotype'), nullable=True),
        sa.Column('trigger_event', sa.Text(), nullable=False),
        sa.Column('trigger_source', sa.String(length=100), nullable=True),
        sa.Column('max_rounds', sa.Integer(), nullable=True),
        sa.Column('avatar_ids', postgresql.ARRAY(postgresql.UUID(as_uuid=True)), nullable=True),
        sa.Column('initial_sentiment', sa.Float(), nullable=True),
        sa.Column('initial_heat', sa.Float(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('final_summary', sa.Text(), nullable=True),
        sa.Column('key_findings', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create simulation_rounds table
    op.create_table('simulation_rounds',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('scenario_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('round_number', sa.Integer(), nullable=False),
        sa.Column('phase', sa.Enum('INITIAL', 'SPREAD', 'DEBATE', 'EVOLUTION', 'CONSENSUS', name='simulationphase'), nullable=True),
        sa.Column('topic', sa.String(length=200), nullable=True),
        sa.Column('topic_keywords', sa.JSON(), nullable=True),
        sa.Column('sentiment_score', sa.Float(), nullable=True),
        sa.Column('sentiment_distribution', sa.JSON(), nullable=True),
        sa.Column('stance_distribution', sa.JSON(), nullable=True),
        sa.Column('heat_score', sa.Float(), nullable=True),
        sa.Column('polarization_index', sa.Float(), nullable=True),
        sa.Column('reach_count', sa.Integer(), nullable=True),
        sa.Column('message_count', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['scenario_id'], ['counterfactual_scenarios.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create agent_responses table
    op.create_table('agent_responses',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('round_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('avatar_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('parent_response_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('response_type', sa.Enum('INITIAL_REACTION', 'REPLY', 'AMPLIFY', 'REFUTE', 'QUESTION', 'JOKE', 'ANALYSIS', 'EMOTIONAL', name='responsetype'), nullable=True),
        sa.Column('sentiment', sa.Float(), nullable=True),
        sa.Column('stance', sa.String(length=20), nullable=True),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('thinking_process', sa.Text(), nullable=True),
        sa.Column('personality_factors', sa.JSON(), nullable=True),
        sa.Column('influence_score', sa.Float(), nullable=True),
        sa.Column('reply_count', sa.Integer(), nullable=True),
        sa.Column('spread_count', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['avatar_id'], ['avatars.id'], ),
        sa.ForeignKeyConstraint(['parent_response_id'], ['agent_responses.id'], ),
        sa.ForeignKeyConstraint(['round_id'], ['simulation_rounds.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create topic_evolutions table
    op.create_table('topic_evolutions',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('scenario_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('topic_name', sa.String(length=200), nullable=False),
        sa.Column('keywords', sa.JSON(), nullable=True),
        sa.Column('evolution_path', sa.JSON(), nullable=True),
        sa.Column('heat_timeline', sa.JSON(), nullable=True),
        sa.Column('key_supporters', sa.JSON(), nullable=True),
        sa.Column('key_opponents', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['scenario_id'], ['counterfactual_scenarios.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_evolutions')
    op.drop_table('agent_responses')
    op.drop_table('simulation_rounds')
    op.drop_table('counterfactual_scenarios')
    
    # Drop enum types
    op.execute('DROP TYPE IF EXISTS responsetype')
    op.execute('DROP TYPE IF EXISTS simulationphase')
    op.execute('DROP TYPE IF EXISTS scenariotype')
    # ### end Alembic commands ###
